build:
  image: golang:1.5
  environment:
    - GO15VENDOREXPERIMENT=0
    - GOOS=linux
    - GOARCH=amd64
    - CGO_ENABLED=0
  commands:
    - go get
    - go build

publish:
  docker:
    username: drone
    password: $$DOCKER_PASS
    email: $$DOCKER_EMAIL
    repo: jswank/gister
    when:
      branch: master

